### ISSUE TITLE
Need to handle invalid wind directions

### ISSUE THREAD

**Issue by matt2005** [Phileep/rflink-to-mqtt#6]
When a invalid wind direction is received it currently converts it to north. Shouldn't it disregard it?

**Comment by Phileep** [comment]
hey Matt

do you have an example of invalid wind data from a raw dump?

I assume it is when you get escape characters interpreted from a transmission?

Would guess we use your non-ascii test, but testing character by character is a bit onerous as it is taking up cycles in the program that could be used for collecting the next signal.

Phil

**Comment by matt2005** [comment]
I changed the sensors battery and now it's ok
